version: '3'

services:
  traefik:
    image: traefik:latest
    ports:
      - 80:80
      - 443:443
      - 8080:8080 # (optional) expose the dashboard - don't use in production?
      - 9001:9001 # phpMyAdmin
    volumes:
      - ./.config/local/traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./.config/local/certs:/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  php:
    image: carletonuniversity/cu-events-api:develop
    restart: always
    volumes:
      - ./laravel:/var/www/html
      - ./.config/local/php/fpm-pool.conf:/usr/local/etc/php-fpm.d/zzz.conf
      - ./.config/local/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    env_file:
      - ./.config/local/env/laravel.env

  nginx:
    image: nginx:latest
    volumes:
      - ./laravel:/var/www/html
      - ./.config/local/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./.config/local/certs:/etc/nginx/certs
    depends_on:
      - php
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.nginx.rule=Host(`localhost`)'
      - 'traefik.http.routers.nginx.entrypoints=web,websecure'
      - 'traefik.http.routers.nginx.tls=true'
      - 'traefik.http.middlewares.nginx.compress=true'
      - 'traefik.http.services.nginx.loadbalancer.server.port=80' # Specify the correct port for NGINX

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./.config/data/mysql:/var/lib/mysql
      - ./.config/data/logs/mysql:/var/log/mysql
      - ./.config/local/mysql:/etc/mysql/conf.d
    environment:
      - MYSQL_DATABASE=api
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_HOST=%
    cap_add:
      - SYS_NICE
    restart: always
    ports:
      - '3307:3306'

  redis:
    image: 'redis:alpine'
    command: redis-server
    expose:
      - '6379'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.phpmyadmin.rule=Host(`localhost`)'
      - 'traefik.http.routers.phpmyadmin.entrypoints=phpmyadmin'
      - 'traefik.http.services.phpmyadmin.loadbalancer.server.port=80'
    restart: always
